### ISSUE TITLE
[PE-D] No delete command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T13-3/tp#172] opened 2021-10-30 06:07 UTC
As a user, I want to delete a specific room or guest, there is no way to achieve this. I do not want to use the clear command as I only want to delete one room/guest not everything 

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: Linxcathyyy/ped#8

**Comment by darrenhoon** [comment] 2021-10-31 04:23
dupe of #166

**Closed by darrenhoon** 2021-10-31 04:23 UTC
